apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forum.fullname" . }}-bbsgo
  labels:
    app: {{ include "forum.name" . }}
    tier: bbsgo
spec:
  replicas: {{ .Values.bbsgo.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "forum.fullname" . }}-bbsgo
  template:
    metadata:
      labels:
        app: {{ include "forum.fullname" . }}-bbsgo
    spec:
      containers:
        - name: bbsgo
          image: {{ .Values.bbsgo.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: BBSGO_ENV
              value: "{{ .Values.bbsgo.env.BBSGO_ENV }}"
            - name: BBSGO_DB_URL
              value: "{{ .Values.bbsgo.env.BBSGO_DB_URL }}"
            - name: BBSGO_BASEURL
              value: "{{ .Values.bbsgo.env.BBSGO_BASEURL }}"
          ports:
            - containerPort: 3000
              name: frontend
            - containerPort: 8082
              name: backend
