apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "forum.fullname" . }}-bbsgo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bbsgo.persistence.storage }}
