apiVersion: v1
kind: Service
metadata:
  name: {{ include "forum.fullname" . }}-bbsgo-fe
  labels:
    app: {{ include "forum.name" . }}
    tier: bbsgo
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: frontend
  selector:
    app: {{ include "forum.fullname" . }}-bbsgo
  type: ClusterIP
