apiVersion: v1
kind: Service
metadata:
  name: {{ include "forum.fullname" . }}-bbsgo-be
  labels:
    app: {{ include "forum.name" . }}
    tier: bbsgo
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: backend
  selector:
    app: {{ include "forum.fullname" . }}-bbsgo
  type: ClusterIP
