apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forum.fullname" . }}-bbsgo-config
data:
  bbs-go.{{ .Values.bbsgo.env.BBSGO_ENV }}.yaml: |-
    Port: {{ .Values.bbsgo.port }}
    BaseUrl: {{ .Values.bbsgo.env.BBSGO_BASEURL }}
    IpDataPath:
    AllowedOrigins:
      - "*"

    # 日志配置
    Logger:
      Filename: /data/logs/bbs-go.log   # 日志文件的位置
      MaxSize: 100                      # 文件最大尺寸（以MB为单位）
      MaxAge: 10                        # 保留旧文件的最大天数
      MaxBackups: 10                    # 保留的最大旧文件数量

    # 数据库连接
    DB:
      Url: "{{ .Values.mysql.username }}:{{ .Values.mysql.password }}@tcp({{ include "forum.fullname" . }}-mysql:{{ .Values.mysql.service.port }})/{{ .Values.mysql.database }}?charset=utf8mb4&parseTime=True&loc=Local"
      MaxIdleConns: 50
      MaxOpenConns: 200

    # 上传配置
    Uploader:
      Enable: aliyunOss
      AliyunOss:
        Host:
        Bucket:
        Endpoint:
        AccessId:
        AccessSecret:
        StyleSplitter: "!"
        StyleAvatar: avatar
        StylePreview: preview
        StyleSmall: 768_auto
        StyleDetail: detail
      # 本地文件上传
      Local:
        Host: https://st.mlog.club/ # 上传文件域名
        Path: /data/www/st.mlog.club # 上传目录

    # 邮件服务器配置，用于邮件通知
    Smtp:
      Host:
      Port:
      Username:
      Password:
      SSL: true

    # 百度SEO相关配置
    BaiduSEO:
      Site:
      Token:

    # 神马搜索SEO相关
    SmSEO:
      Site:
      UserName:
      Token:

    # es 配置
    Es:
      Url:
      Index:

    # 微信配置
    WeixinConfig:
      AppID:
      AppSecret:

    # search
    Search:
      IndexPath: # 索引路径
