apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forum.fullname" . }}-bbsgo
  labels:
    app: bbsgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbsgo
  template:
    metadata:
      labels:
        app: bbsgo
    spec:
      containers:
      - name: bbsgo
        image: "{{ .Values.bbsgo.img.repository }}:{{ .Values.bbsgo.img.tag }}"
        imagePullPolicy: {{ .Values.bbsgo.img.pullPolicy }}
        ports:
          - containerPort: {{ .Values.bbsgo.port }}
        env:
          - name: BBSGO_ENV
            value: "{{ .Values.bbsgo.env.BBSGO_ENV }}"
        volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: config-volume
            mountPath: /app/bbs-go/server/bbs-go.{{ .Values.bbsgo.env.BBSGO_ENV }}.yaml
            subPath: bbs-go.{{ .Values.bbsgo.env.BBSGO_ENV }}.yaml
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "forum.fullname" . }}-bbsgo-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "forum.fullname" . }}-bbsgo-pvc
