apiVersion: v1
kind: Service
metadata:
  name: {{ include "forum.fullname" . }}-fe
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "forum.name" . }}-fe
spec:
  ports:
    - port: {{ .Values.fe.service.port }}
      targetPort: {{ .Values.fe.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "forum.fullname" . }}-fe
  type: ClusterIP
