{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "forum.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- with .Values.ingress.annotations }}
{{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ (index .Values.ingress.tls 0).secretName | default "forum-tls" }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "forum.fullname" . }}-fe
                port:
                  number: {{ .Values.fe.service.port }}
{{- end }}
