apiVersion: v1
kind: Service
metadata:
  name: {{ include "forum.fullname" . }}-phpmyadmin
  labels:
    app: {{ include "forum.name" . }}
    tier: phpmyadmin
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.phpmyadmin.service.port }}
      protocol: TCP
      name: phpmyadmin
  selector:
    app: {{ include "forum.fullname" . }}-phpmyadmin
  type: ClusterIP
