ingress:
  enabled: true
  host: forum.eng.atomi.ai
  annotations: {}
  tls: 
    - secretName: forum-tls

mysql:
  image: mysql:8.0
  username: bbsgo
  password: "123456"
  rootPassword: "123456"
  database: bbsgo_db
  service:
    port: 3306
  persistence:
    enabled: true
    storageClass: local-path   # 此处指定集群默认 StorageClass 的名称
    accessMode: ReadWriteOnce
    size: 8Gi

fe:
  image: lamuguo/bbs_go_fe_runtime:latest
  replicaCount: 1
  service:
    port: 3000

bbsgo:
  env:
    BBSGO_ENV: k8s
    BBSGO_BASEURL: "http://127.0.0.1:3000"
  port: 8082
  replicaCount: 1
  img:
    repository: lamuguo/bbsgo_backend
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    storage: 10Gi
