name: bbs-go-site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: site/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./site
        run: |
          pnpm install
      - name: Build
        working-directory: ./sitehttps://hub.docker.com/repository/docker/lamuguo/bbsgo_backend
        run: |
          pnpm build


  build-and-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: lamuguo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Login to Docker Hub
        run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --target fe_runtime -t ${{ env.DOCKERHUB_USERNAME }}/bbs_go_fe_runtime:latest .

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/bbs_go_fe_runtime:latest
                  